### ISSUE TITLE
Configured theme not applying to all applications

### ISSUE THREAD

**Issue by Scraft161** [trialuser02/qt6ct#38]
I've used qt5ct and qt6ct to set custom styles for my qt apps, this works great for most apps and I've been using that.
But there's a bit of snag, KDE Connect and Tokodon seem to ignore the configured style.

![An image with "Ark" on the left with the style applied and "Tokodon" and "KDE Connect" on the right with their default styling](https://github.com/trialuser02/qt6ct/assets/19813118/cf6b058b-1e4f-4ab6-9c24-47a2c58bf434 "An image with `Ark` on the left with the style applied and `Tokodon` and `KDE Connect` on the right with their default styling")  
Ark left has the theme applied; whilst Tokodon and KDE Connect fall back to their default light theme.

I have noticed that Kde Connect and Tokodon are a bit different compared to other Qt apps with a header bar and more mobile-forward and responsive layout; but I don't see why they wouldn't be styled by the Qt theme.

I can however confirm that this shouldn't be a configuration issue as both Qt5 and Qt6 applications work fine and without any major issues.

**Comment by Scraft161** [comment]
little follow-up that provides more information:

I did some digging and apparently both KDE Connect and Tokodon are built with Kirigami, whatever may be the cause is probably in relation to that.
What exactly is at play here, I don't know, but it does seem like a good place to start investigating.

In fact, I found [this reddit thread](https://www.reddit.com/r/kde/comments/117b1ai/kirigami_apps_not_following_qt5ct_or_qt6ct_in/) talking about the exact issue at hand; but it doesn't seem to point to anything that could be of use.

**Comment by ilya-fedin** [comment]
KDE uses its own color scheme engine called KColorScheme (ignoring QPalette and Qt theme colors) and Kirigami applications are built on top of QML that qt5ct has no theme control for. The Qt's default for QML applications is the Fusion theme on Linux (just like for widgets) but KDE has its own theme called qqc2-desktop-style that allows applying widgets themes to QML applications. KDE applications are also made for their own icon engine called KIconEngine that applies KDE color schemes to svg icons so when the engine is not used you're likely to see things like black icons on black background.

I have a patch adding support KColorScheme/KIconEngine/qqc2-desktop-style support to qt5ct, packages with it are available for [NixOS](https://github.com/ilya-fedin/nur-repository/tree/master/pkgs/qt5ct) and qt{5,6}ct-kde on AUR.

An important thing is to have a KDE color scheme for your Qt theme and apply it in the patched qt5ct. It enumerates such color schemes but doesn't show a difference in preview (as I'm too lazy to implement this, it's good for me as is).

**Comment by Vistaus** [comment]
Kirigami is not the issue, as it also doesn't apply to KDE 6 apps like Dolphin and System Settings using qt6ct.

**Comment by ilya-fedin** [comment]
System Settings do use Kirigami. Although you're right that it's not only Kirigami, it's KColorScheme framework which is used by both QML and Widgets KDE apps.

**Comment by Vistaus** [comment]
But does Dolphin use Kirigami? And Haruna? And Amarok git, built with Qt 6? And Okular? Because it doesn't work in those apps either. And if System Settings only partly uses Kirigami, I'd expect the theme to at least partially apply.

Btw, I tried your patch on Arch Linux with qt6ct from git, but it doesn't solve the issue.

**Comment by ilya-fedin** [comment]
As I said, it's not Kirigami but KColorScheme. And yes, all KDE applications use KColorScheme.

> Btw, I tried your patch on Arch Linux with qt6ct from git, but it doesn't solve the issue.

Did you choose a color scheme with it that has a `(KColorScheme)` in its name?

**Comment by Vistaus** [comment]
But then what changed with KDE 6? Because I never had issues like this with KDE 5 apps.

Yes, I chose Breeze Dark. That's one of the two default KDE themes, so it should be good. Except that it isn't.

**Comment by ilya-fedin** [comment]
> Yes, I chose Breeze Dark. That's one of the two default KDE themes, so it should be good. Except that it isn't.

Can you provide your Qt-related environment variables? `env | grep QT`

**Comment by Vistaus** [comment]
```
❯ env | grep QT
QT_AUTO_SCREEN_SCALE_FACTOR=0
QT_WAYLAND_RECONNECT=1
QT_QPA_PLATFORMTHEME=qt6ct
```

**Comment by ilya-fedin** [comment]
Can you reproduce if you run affected application in that terminal session?

**Comment by Vistaus** [comment]
> Can you reproduce if you run affected application in that terminal session?

Then it seems to work fine.

**Comment by Vistaus** [comment]
Scratch that: it did apply the correct colors, but not the theming engine.

**Comment by ilya-fedin** [comment]
> Then it seems to work fine.

So the issue is that you have set `QT_QPA_PLATFORMTHEME` in a way it doesn't go through all your graphical session

**Comment by Vistaus** [comment]
> > Then it seems to work fine.
> 
> So the issue is that you have set `QT_QPA_PLATFORMTHEME` in a way it doesn't go through all your graphical session

Please see my message after that one. 🙂

(And I have set that variable in /etc/environment, just like I used to do with qt5ct.)

**Comment by ilya-fedin** [comment]
> Scratch that: it did apply the correct colors, but not the theming engine.

Some KDE applications like Dolphin hardcode theme for non-KDE sessions now

**Comment by ilya-fedin** [comment]
see https://invent.kde.org/frameworks/kiconthemes/-/issues/3

**Comment by Vistaus** [comment]
> > Scratch that: it did apply the correct colors, but not the theming engine.
> 
> Some KDE applications like Dolphin hardcode theme for non-KDE sessions now

But I'm using KDE.

**Comment by ilya-fedin** [comment]
> But I'm using KDE.

Then you don't really need qt6ct? Setting qt6ct would make that logic to think you're using a non-KDE session.

**Comment by Vistaus** [comment]
> > But I'm using KDE.
> 
> Then you don't really need qt6ct? Setting qt6ct would make that logic to think you're using a non-KDE session.

But using qt6ct I can disable cursor blinking, which is not supported by KDE itself. I was advised to use qt5ct for that on KDE 5, but I clean installed Arch Linux with KDE 6 last week, so now I need to use qt6ct to achieve that. And because of that, I also need to set the theming engine through qt6ct.

**Comment by ilya-fedin** [comment]
That logic seem to force the Qt style from kdeglobals so setting it via both qt6ct and system settings should theoretically do the thing

**Comment by Vistaus** [comment]
Could you explain that a bit more? Like I said: I did use this exact same setup with qt5ct without any issues.

**Comment by ilya-fedin** [comment]
> Could you explain that a bit more

You don't know how to set Qt style via system settings?

> Like I said: I did use this exact same setup with qt5ct without any issues.

As you can see the linked issue in kiconthemes, it's done in KF6, not KF5

**Comment by Vistaus** [comment]
I have set it in system settings, but it doesn’t make a difference for the majority of apps, including the ones I listed earlier.

**Comment by ilya-fedin** [comment]
What those commands return?
```
grep widgetStyle ~/.config/kdeglobals 
grep style ~/.config/qt6ct/qt6ct.conf
```

**Comment by Vistaus** [comment]
```
❯ grep widgetStyle ~/.config/kdeglobals 
widgetStyle=qt6ct-style

~
❯ grep style ~/.config/qt6ct/qt6ct.conf
style=kvantum
stylesheets=@Invalid()
toolbutton_style=2

~
❯ 
```

**Comment by ilya-fedin** [comment]
Could it be that you have kvantum installed only for Qt 5?

**Comment by Vistaus** [comment]
Nope, kvantum-qt6 is installed and qt6ct and FeatherNotes do use the Kvantum theme I set, so it's partly functioning.

**Comment by ilya-fedin** [comment]
The only idea is maybe there's a miscommunication. Can you upload a screenshot of how it looks wrongly and (if possible) how it should look like?

**Comment by Vistaus** [comment]
I have no idea what changed, but suddenly it's working now. Thanks for all of your help! 🙂

**Comment by Vistaus** [comment]
Actually, scratch that: it works for a moment in for example Dolphin, but when I close Dolphin, it reverts to Breeze. Then I re-apply qt6ct as theme engine in System Settings and Dolphin looks fine again until I close it…

**Comment by Vistaus** [comment]
![Schermafdruk_20240926_181450](https://github.com/user-attachments/assets/fa17cfc3-6c97-4f5a-b640-edf80f0df225)
Here's an example of what Dolphin is supposed to look like with Kvantum enabled in qt6ct. And it does, until I close Dolphin. Then I have to re-apply qt6ct in System Settings. And Dolphin is just one example, but there are more apps where this issue is present. But not all of them: for example, Lokalize and FeatherNotes behave fine.

**Comment by ilya-fedin** [comment]
> Here's an example of what Dolphin is supposed to look like with Kvantum enabled in qt6ct.

but how it looks when it's broken?

**Comment by ilya-fedin** [comment]
> And it does, until I close Dolphin. Then I have to re-apply qt6ct in System Settings.

Does it get removed from kdeglobals?

**Comment by Vistaus** [comment]
> > Here's an example of what Dolphin is supposed to look like with Kvantum enabled in qt6ct.
> 
> but how it looks when it's broken?

Those apps fall back to Breeze then.

**Comment by Vistaus** [comment]
> > And it does, until I close Dolphin. Then I have to re-apply qt6ct in System Settings.
> 
> Does it get removed from kdeglobals?

How do I check that?

**Comment by ilya-fedin** [comment]
> grep widgetStyle ~/.config/kdeglobals

this

**Comment by ilya-fedin** [comment]
> Those apps fall back to Breeze then.

I mean there are different parts of Breeze (widget style, color scheme, etc), it would be useful to see which exactly parts get changed

**Comment by Vistaus** [comment]
> > grep widgetStyle ~/.config/kdeglobals
> 
> this

```
❯ grep widgetStyle ~/.config/kdeglobals
widgetStyle=qt6ct-style
```

**Comment by Vistaus** [comment]
> > Those apps fall back to Breeze then.
> 
> I mean there are different parts of Breeze (widget style, color scheme, etc), it would be useful to see which exactly parts get changed

![Schermafdruk_20240926_200433](https://github.com/user-attachments/assets/e01b6c47-efff-4e56-8843-eddc97b40093)

**Comment by ilya-fedin** [comment]
Looks like I found what is wrong. System Settings sets
```
[KDE]
widgetStyle=qt6ct-style
```

While KConfigWidgets framework expects
```
[General]
widgetStyle=qt6ct-style
```
So adding tho two lines to kdeglobals should help.

I wonder whether that's a bug in kconfigwidgets...

**Comment by Vistaus** [comment]
That seems to have solved it forgood! Thank you so, so much for all of your help - I truly appreciate it! 🙂

And yeah, that seems to be a bug that needs to be reported, most likely on bugs.kde.org.

**Comment by ilya-fedin** [comment]
I tried to ask Cristoph Cullmann on Matrix, will see what he answers

**Comment by kbroulik** [comment]
> But using qt6ct I can disable cursor blinking, which is not supported by KDE itself.

Put into `~/.config/kdeglobals`
```
[KDE]
CursorBlinkRate=0
```

Now stop using qt6ct within plasma, thank you.

**Comment by Vistaus** [comment]
> I tried to ask Cristoph Cullmann on Matrix, will see what he answers

Thanks. 🙂

**Comment by Vistaus** [comment]
> > But using qt6ct I can disable cursor blinking, which is not supported by KDE itself.
> 
> Put into `~/.config/kdeglobals`
> 
> ```
> [KDE]
> CursorBlinkRate=0
> ```
> 
> Now stop using qt6ct within plasma, thank you.

So they've finally added that option? Great, thanks! I'll try it. 🙂

**Comment by kbroulik** [comment]
That option has always been there, there’s just no GUI to it.

**Comment by Vistaus** [comment]
> That option has always been there, there’s just no GUI to it.

I was told in the past it wasn't there or it wasn't available on Wayland or something, so I got recommended to use qt5ct. And then with KDE 6, I figured I would need qt6ct. Odd that people didn't know it was available all along then, but oh well.

**Comment by ilya-fedin** [comment]
> I tried to ask Cristoph Cullmann on Matrix, will see what he answers

He ignored my question on Matrix so I ended up asking on https://invent.kde.org/frameworks/kiconthemes/-/issues/3#note_1042812. That's a bug indeed.

**Comment by Vistaus** [comment]
Thanks! 🙂

**Comment by ilya-fedin** [comment]
FWIW, looks like there's a long-standing bug in Kirigami applying platform palette outside of KDE. Replacing `property font defaultFont: fontMetrics.font` line with `defaultFont: fontMetrics.font` in /usr/lib/qt6/qml/org/kde/kirigami/styles/org.kde.desktop/Theme.qml (this is path for Arch, might be different in other distros) should make Kirigami apps to follow system palette even without patches to qt6ct.

It basically doesn't initialize the component responsible to apply platform palette due to this bug that causes type error on component initialization.

**Comment by ilya-fedin** [comment]
> FWIW, looks like there's a long-standing bug in Kirigami applying platform palette outside of KDE.

Should be fixed with KF 6.8 so Kirigami applications should start to follow QPalette just like widgets applications

**Comment by Vistaus** [comment]
Sadly, it's not fixed entirely. System Settings look better now, but Dolphin is totally broken now. I switched to LXQt in the mean time, btw, so I'm not even on KDE anymore.

**Comment by ilya-fedin** [comment]
> but Dolphin is totally broken now

Dolphin uses their new approach of hardcoding theme outside of KDE, it now follows only kdeglobals for widget style and icon theme and xdg-desktop-portal's color-scheme spec for the light/dark color scheme switch.

#43 takes care about all that

**Comment by ilya-fedin** [comment]
> He ignored my question on Matrix so I ended up asking on https://invent.kde.org/frameworks/kiconthemes/-/issues/3#note_1042812. That's a bug indeed.

(that bug was fixed too so setting widget style via systemsettings app should work just as well but still portal is needed for proper dark mode without #43)

**Comment by Vistaus** [comment]
> > He ignored my question on Matrix so I ended up asking on https://invent.kde.org/frameworks/kiconthemes/-/issues/3#note_1042812. That's a bug indeed.
> 
> (that bug was fixed too so setting widget style via systemsettings app should work just as well but still portal is needed for proper dark mode without #43)

Sadly, the bug isn't fixed for me.

**Comment by Vistaus** [comment]
> > He ignored my question on Matrix so I ended up asking on https://invent.kde.org/frameworks/kiconthemes/-/issues/3#note_1042812. That's a bug indeed.
> 
> (that bug was fixed too so setting widget style via systemsettings app should work just as well but still portal is needed for proper dark mode without #43)

Cool, thanks. 🙂

**Comment by ilya-fedin** [comment]
> Sadly, the bug isn't fixed for me.

wdym? Setting widget style via systemsettings still doesn't work for you?

**Comment by Vistaus** [comment]
Nope, still doesn't work.

Also, I just tried your qt6ct branch, but it didn't fix the Dolphin issue. :/

**Comment by ilya-fedin** [comment]
> Nope, still doesn't work.

Did you restart apps after changing it? It doesn't apply on the fly.

> Also, I just tried your qt6ct branch, but it didn't fix the Dolphin issue. :/

What exactly issue do you have now?

**Comment by Vistaus** [comment]
I did restart apps, but it didn't work.

The issue I have now is that Dolphin uses a weird color scheme, with black and white markings, and black text on a black background in the sidebar. Before the 6.8 update, Dolphin looked fine (white text on a black background and no white markings). Your branch sadly didn't fix it.
![Schermafdruk_20241109_160902](https://github.com/user-attachments/assets/9761e59d-0b35-4cac-b4e0-7c9ecf2e9669)

**Comment by ilya-fedin** [comment]
From that screenshot it looks like widget style successfully applied after all? Color scheme gets applied from portal settings as I explained before, not from systemsettings.

> Your branch sadly didn't fix it.

Did you set the color scheme with `(KColorScheme)` in the name? Are you sure qt6ct was actually used?

**Comment by Vistaus** [comment]
Sorry, I didn't mean the widget style didn't apply. I mean switching styles from System Settings doesn't work. But once I set one manually like we figured out earliel in the thread, it does apply.

I did set that color scheme and I most definitely used qt6ct.

**Comment by ilya-fedin** [comment]
> I mean switching styles from System Settings doesn't work. But once I set one manually like we figured out earliel in the thread, it does apply.

Are you sure you have kconfigwidgets 6.7.0 or later?

**Comment by Vistaus** [comment]
Yes, I'm on Arch and I received that update. But I don't care much for that bug, to be honest. Manually editing the config file is not such a hassle. I'd rather have a readable Dolphin back lol.

**Comment by ilya-fedin** [comment]
> Yes, I'm on Arch and I received that update.

That's very weird cause it works for me now:

https://github.com/user-attachments/assets/76412cf3-3b65-43d5-9586-557dcdf36660

> But I don't care much for that bug, to be honest. Manually editing the config file is not such a hassle. I'd rather have a readable Dolphin back lol.

Maybe that's somehow related to the fact you can't get it... Did you try running from terminal like `QT_QPA_PLATFORMTHEME=qt6ct dolphin`? What settings do you have in qt6ct?

**Comment by Vistaus** [comment]
Yep, Dolphin looks the exact same with that command. I have set it to Kvantum.

**Comment by ilya-fedin** [comment]
> I have set it to Kvantum.

I mean maybe you can provide a screenshot of qt6ct settings or the content of `~/.config/qt6ct/qt6ct.conf`?

**Comment by Vistaus** [comment]
Sure, here you go:

```
[Appearance]
color_scheme_path=/usr/share/qt6ct/colors/darker.conf
custom_palette=false
icon_theme=Fluent-dark
standard_dialogs=kde
style=kvantum

[Fonts]
fixed="DejaVu Sans,16,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,Book"
general="DejaVu Sans,16,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,Book"

[Interface]
activate_item_on_single_click=0
buttonbox_layout=2
cursor_flash_time=0
dialog_buttons_have_icons=2
double_click_interval=400
gui_effects=@Invalid()
keyboard_scheme=3
menus_have_icons=true
show_shortcuts_in_context_menus=true
stylesheets=@Invalid()
toolbutton_style=2
underline_shortcut=1
wheel_scroll_lines=3

[SettingsWindow]
geometry="@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x5\x41\0\0\x2\x82\0\0\b\xd7\0\0\x6,\0\0\x5G\0\0\x2\xa0\0\0\b\xd1\0\0\x6&\0\0\0\0\0\0\0\0\xf\0\0\0\x5G\0\0\x2\xa0\0\0\b\xd1\0\0\x6&)"

[Troubleshooting]
force_raster_widgets=1
ignored_applications=@Invalid()
```

**Comment by ilya-fedin** [comment]
I have asked:

> Did you set the color scheme with `(KColorScheme)` in the name?

You answered:

> I did set that color scheme and I most definitely used qt6ct.

But this one

> color_scheme_path=/usr/share/qt6ct/colors/darker.conf

Is not a KColorScheme.

**Comment by ilya-fedin** [comment]
Important thing is to choose a color scheme containing `(KColorScheme)` in name (such as Breeze Dark) as non-KDE color schemes (such as darker) won't KDE applications properly.

**Comment by Vistaus** [comment]
I know, but in the GUI of qt6ct it is set to Default and not the darker color scheme. So then it must be a bug in qt6ct.

**Comment by ilya-fedin** [comment]
Right, your config also has

> custom_palette=false

But my point is that it won't work with neither Default nor darker. You need a KColorScheme for KDE applications to look properly. In the Plasma session, you always have a KDE color scheme set (Breeze Light by default).

**Comment by Vistaus** [comment]
I have a KColorScheme set.

**Comment by ilya-fedin** [comment]
But the config says you don't. You have `custom_palette=false` and `color_scheme_path=/usr/share/qt6ct/colors/darker.conf`.

**Comment by ilya-fedin** [comment]
Maybe you configure qt5ct instead of qt6ct?

**Comment by Vistaus** [comment]
Then there still is a bug somewhere, either in qt6ct or in KDE's systemsettings.

**Comment by Vistaus** [comment]
> Maybe you configure qt5ct instead of qt6ct?

Nope.

**Comment by ilya-fedin** [comment]
> Then there still is a bug somewhere, either in qt6ct or in KDE's systemsettings.

Hm. Can you provide a screenshot of your qt6ct settings (the first tab)?

**Comment by Vistaus** [comment]
Sure, here you go.

![Schermafdruk_20241110_201708](https://github.com/user-attachments/assets/f65d40c2-39e3-43d2-a00c-e2cae9d03d1d)

**Comment by ilya-fedin** [comment]
You don't have a KColorScheme set
![](https://github.com/user-attachments/assets/6b7a0287-f3d2-47b4-9962-97a68cb029cf)
The radio box has to be set to "Aangepast" and the drop down list to a value containing `(KColorScheme)` in name (and that provides a dark color scheme, of course).

**Comment by Vistaus** [comment]
But the color scheme from KDE systemsettings I have set is not available in that drop down list.

**Comment by ilya-fedin** [comment]
> Also, I just tried your qt6ct branch

> But the color scheme from KDE systemsettings I have set is not available in that drop down list.

Are you sure you're using my branch? It's available only there.

**Comment by Vistaus** [comment]
Yes, I have manually compiled your branch qt6ct ‘shenenigans’.

**Comment by ilya-fedin** [comment]
> Yes, I have manually compiled your branch qt6ct ‘shenenigans’.

Are you sure you have no other qt6ct instance installed? Maybe you're launching that one instead of the compiled one.

**Comment by ilya-fedin** [comment]
On Arch you can just install qt6ct-kde package from AUR.

**Comment by Vistaus** [comment]
Nope, other one is not installed anymore. And qt6ct-kde from AUR also doesn't have the correct color scheme in the drop-down list.

**Comment by ilya-fedin** [comment]
> And qt6ct-kde from AUR also doesn't have the correct color scheme in the drop-down list.

I wonder where the correct color scheme is located in the file system?

**Comment by Vistaus** [comment]
I just installed qt6ct-kde yet again and now it finally shows other color schemes in the dropdown list.

![Schermafdruk_20241110_212103](https://github.com/user-attachments/assets/fd73dced-f9b4-4636-b194-f0e0526dd809)

However, Dolphin still looks the same. :(

**Comment by ilya-fedin** [comment]
Even if you launch it with `QT_QPA_PLATFORMTHEME=qt6ct dolphin`?

**Comment by Vistaus** [comment]
No, then it looks right. I guess there's a bug in Arch somewhere then.

**Comment by ilya-fedin** [comment]
It might be not easy to override QT_QPA_PLATFORMTHEME in a Qt desktop environment such as LXQt...

**Comment by ilya-fedin** [comment]
If xdg-desktop-portal-lxqt supported org.freedesktop.appearance.color-scheme parameter, it would just work I guess, even without qt6ct...

**Comment by ilya-fedin** [comment]
If merged, this should restore the possibility to change color scheme via kdeglobals when there's no portal.
https://invent.kde.org/frameworks/kcolorscheme/-/merge_requests/28

**Comment by Vistaus** [comment]
Great! Thanks for putting the time into that MR. 🙂

**Comment by ilya-fedin** [comment]
@Vistaus I was told you can specify your color scheme like
```
[UiSettings]
ColorScheme=Sonomatic
```
Usually it gets specified in app config file (e.g. `dolpinrc`) but it seem to also work with Dolphin when specified in kdeglobals from my testing.

On other hand, applications having color scheme chooser in UI (e.g. Elisa) seem to write ColorScheme setting with empty value to their config file if it isn't present what shadows the value in kdeglobals. But then you can easily select your color scheme in their UI.

**Comment by ilya-fedin** [comment]
If no answer, I would assume it works and will close the kcolorscheme MR
